---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/clusterctl version
    register: cluster_api_test_output
  - name: clusterctl version
    debug:
      msg: '{{ cluster_api_test_output.stdout }}'
